version: '3'

services:
  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: adminPWD
      MYSQL_DATABASE: users
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: